### ISSUE TITLE
Bug in datetime_convert.java

### ISSUE THREAD

**Issue by Sean-300** [yonimasha/Charlie-s-Repository#10]
Description: Missing semicolon on line 8, compiler error

Steps to Reproduce: The program will not compile, IDE should show error (missing semicolon)

Expected Behavior: The line was declaring and initializing a string to a value.

Actual Behavior: The file will not compile

Screenshots: Not needed

Additional Information: N/A

Operating System: Windows 11
Browser: Google Chrome
Version: Latest Chrome
Any other relevant information: Testing java code in Eclipse IDE

Possible Solution: Adding a semicolon to the end of the line

Related Issues: N/A

Priority: High priority (easy and obvious fix), but technically grinds program to a halt since it is a compile-time error.

Reproducibility: Error will always occur until semicolon is added

Impact: Low impact, as this line will not cause any additional problems for the program once fixed.

**Comment by yonimasha** [comment]
Fixed bug by adding semicolon to line that didn't have one
