### ISSUE TITLE
rgb_to_hex python function severely broken (PLEASE FIX NOW URGENT)

### ISSUE THREAD

**Issue by yonimasha** [yonimasha/Charlie-s-Repository#11]
Description: Formatting very incorrect for the hexadecimal number

Steps to Reproduce

1. Run rgb_to_hex with any values
2. Observe how the hexadecimal string is incorrect in terms of formatting

Expected Behavior: test with hex_color = rgb_to_hex(255, 127, 0) -> returns "FF7F00"

Actual Behavior: printed out '7FFF7F'

Additional Information: 

Operating System: Mac OS
Browser: Chrome
Version: macOS Ventura 13.2.1

Possible Solution: g is repeated onto blue so maybe change the g to a b. Also formatting on return
statement looks off (grb or rgb?)

Priority How critical is this issue/bug? Low, medium, or high priority? VERY CRITICAL FIX NOW

Reproducibility: always

Impact What is the impact of this issue/bug? Low, medium, or high? HIGH

**Comment by Sean-300** [comment]
Fixed these issues in rgb_to_hex.py by getting the order of r, g, b correct and making sure to use the right variable names respectively for each r, g, b line.
