### ISSUE TITLE
Bug in sum_even_fibonacci.java

### ISSUE THREAD

**Issue by yonimasha** [yonimasha/Charlie-s-Repository#14]
Description: while loop not running

Steps to Reproduce

1. run program

Expected Behavior: should run program fine with sumEven returning some number not 0

Actual Behavior: sumEven will be 0

Operating System: macOS
Browser: chrome
Version: Ventura

Possible Solution: check the conditions for the while loop

Priority: HIGH

Reproducibility: ALWAYS

Impact: HIGH

**Comment by adimento** [comment]
Changed 1 to zero in if statement to correctly check if number is even
