### ISSUE TITLE
sum_even_fibonacci.py

### ISSUE THREAD

**Issue by Charlie-Corriero** [yonimasha/Charlie-s-Repository#9]
Expected Behavior: Print the sum of the even fibonacci numbers
Actual Behavior: Always prints 0
Screenshots: None needed
Operating System: macOS
Version: Ventura 13.1
Possible solution: Change the '==' in line 6 to '!='
Related Issues: None
Priority: High
Reproducibility: Always
Impact: High

**Comment by yonimasha** [comment]
Fixed the issue Charlie by fixing logic errors. Have a great week! Hope the kids are doing good.
